### ISSUE TITLE
Makefile has hardcoded paths

### ISSUE THREAD

**Issue by lidarwin** [sagor999/poker_ml#3]
https://github.com/sagor999/poker_ml/blob/60d75e164930b2b03da7ed96d054062ba1173883/card_recognizer_ml/Makefile#L10

I'm not too familiar with docker, but it seems there are hardcoded paths here... Any tips on how I would change it to my machine? 

1) Is `tf-gpu` a directory where tensorflow is installed?

2) Also what is `$$(pwd)/data:/data -v $$(pwd):/src`

3) I have nvidia gpu with nvidia graphics driver installed, but do I need anything to make sure `--runtime=nvidia` works?

**Comment by sagor999** [comment]
`$$(pwd)/data:/data -v $$(pwd):/src` so if you are running this from `poker_ml/card_recognizer_ml` folder, this would map:
`poker_ml/card_recognizer_ml/data` folder to a `/data` folder inside docker container
`poker_ml/card_recognizer_ml` folder to a `/src` folder inside docker container.

`paveltumik/tf-gpu:latest` is the name of the image to use for container. 
https://github.com/sagor999/poker_ml/blob/60d75e164930b2b03da7ed96d054062ba1173883/card_recognizer_ml/Makefile#L12
if you run `make image` it will create that image for you locally. If you will plan on pushing this image into docker registry, then you will need to update `paveltumik/` to your own repo. But if you only using it locally it will work as is.

3. I think it should work as is. Though I tested this on Ubuntu 20.04 I believe. Not sure which OS you are using, but since everything runs in docker container it technically shouldn't matter.

**Comment by lidarwin** [comment]
Thanks for clearing up the image for the container.
When I run `make run` in the root path, I get the error:
`docker run --name card_ml --runtime=nvidia -t -d -v $(pwd)/data:/data -v $(pwd):/src --rm paveltumik/tf-gpu:latest bash
docker: Error response from daemon: Unknown runtime specified nvidia.
`
It seems that the `--runtime=nvidia` is causing me issues. Any advice on how to debug this? I have nvidia graphics driver installed for my graphics card and am running Ubuntu 20.04.3 LTS
